dist: trusty
sudo: false
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
  apt:
    packages:
    - rpm
    - fakeroot

before_install:
  # 2016-10: Apple doesn't include openssl any more because of security
  # problems openssl had. Manually specify path to includes/libs.
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export CPPFLAGS="-I/usr/local/opt/openssl/include"; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export LDFLAGS="-L/usr/local/opt/openssl/lib"; fi
  - pip install conan
  - conan remote add joystream https://conan.joystream.co:9300 True
  - conan user travis -p trav444 -r=joystream
install:
  - npm install -g electron-forge
  # make sure to install same version as electron in package.json to test version which will be published
  - npm install -g electron-prebuilt-compile@1.6.4
  - npm install -g electron-rebuild

before_script:
  # fix for electron-mocha unit tests to work
  - if [ "$TRAVIS_OS_NAME" = linux ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

script:
  - npm install
  - mkdir ~/.electron-gyp
  - ln -s $HOME/.conan $HOME/.electron-gyp/.conan
  # rebuild native addons for electron - unit tests use electron-mocha
  - electron-rebuild
  - npm test

before_deploy:

deploy:
  provider: script
  skip_cleanup: true
  script: electron-forge publish
  on:
    branch:
      - release*
