dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
  apt:
    packages:
    - rpm
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi'
  - pip install conan
  - conan remote add joystream https://conan.joystream.co:9300 True
  - conan user travis -p trav444 -r=joystream
install:
  - npm install -g electron-forge
  - npm install
script:
  - npm test
before_deploy:
  - ln -s ~/.conan ~/.electron-gyp
deploy:
  provider: script
  skip_cleanup: true
  script: BCOIN_NO_NATIVE=1 electron-forge publish
  on:
    branch:
      - development
      - travis
